/**
 * Opus WASM API wrapper
 *
 * Simplified version adapted from vendor/libopus-wasm
 * Focuses on encoder functionality needed for audio recording
 */

import type {
  OpusDecoderHandle,
  OpusDecoderOptions,
  OpusEncoderHandle,
  OpusEncoderOptions,
  OpusError,
} from "./types"
import { OpusError as OpusErrorClass } from "./types"

// This will be the WASM module type (generated by emscripten)
type LibopusModule = any // Will be properly typed in types.d.mts

// Application constants (from opus_defines.h)
const OPUS_APPLICATION_VOIP = 2048
const OPUS_APPLICATION_AUDIO = 2049
const OPUS_APPLICATION_RESTRICTED_LOWDELAY = 2051

// CTL constants
const OPUS_SET_BITRATE_REQUEST = 4002
const OPUS_SET_COMPLEXITY_REQUEST = 4010
const OPUS_SET_INBAND_FEC_REQUEST = 4012
const OPUS_SET_PACKET_LOSS_PERC_REQUEST = 4014
const OPUS_SET_DTX_REQUEST = 4016
const OPUS_SET_VBR_REQUEST = 4006

const OPUS_AUTO = -1000
const OPUS_BITRATE_MAX = -1

let modulePromise: Promise<LibopusModule> | undefined

/**
 * Get or create the WASM module singleton
 */
async function getModule(): Promise<LibopusModule> {
  if (!modulePromise) {
    // Dynamic import of the WASM module
    // @ts-expect-error WASM module type
    const createLibopusModule = (await import("./libopus.wasm.mjs")).default
    modulePromise = createLibopusModule()
  }
  return modulePromise
}

/**
 * Create Opus error from error code
 */
function createOpusError(
  module: LibopusModule,
  code: number,
  operation: string
): OpusError {
  const message = module.UTF8ToString(module._oc_strerror(code))

  const codeNames: Record<string, string> = {
    "-1": "BadArg",
    "-2": "BufferTooSmall",
    "-3": "InternalError",
    "-4": "InvalidPacket",
    "-5": "Unimplemented",
    "-6": "InvalidState",
    "-7": "AllocFail",
  }

  const codeName = codeNames[code.toString()] ?? "UnknownError"
  return new OpusErrorClass(message, code, codeName, operation)
}

/**
 * Map application string to constant
 */
function mapApplication(app: "audio" | "voip" | "lowdelay"): number {
  switch (app) {
    case "voip":
      return OPUS_APPLICATION_VOIP
    case "audio":
      return OPUS_APPLICATION_AUDIO
    case "lowdelay":
      return OPUS_APPLICATION_RESTRICTED_LOWDELAY
  }
}

/**
 * Map bitrate string to constant
 */
function mapBitrate(bitrate: number | "auto" | "max"): number {
  if (typeof bitrate === "number") return bitrate
  if (bitrate === "auto") return OPUS_AUTO
  if (bitrate === "max") return OPUS_BITRATE_MAX
  return 64000 // default
}

/**
 * Create Opus encoder
 */
export async function createOpusEncoder(
  options: OpusEncoderOptions
): Promise<OpusEncoderHandle> {
  const module = await getModule()

  const sampleRate = options.sampleRate
  const channels = options.channels
  const application = mapApplication(options.application ?? "audio")
  const frameSize = options.frameSize ?? Math.floor((sampleRate / 1000) * 20) // 20ms default

  // Create encoder
  const errorPtr = module._malloc(4)
  let encoderPtr: number

  try {
    encoderPtr = module._oc_create_encoder(
      sampleRate,
      channels,
      application,
      errorPtr
    )
    const error = module.HEAP32[errorPtr >> 2]!

    if (!encoderPtr || error !== 0) {
      throw createOpusError(module, error, "createEncoder")
    }
  } finally {
    module._free(errorPtr)
  }

  // Apply encoder settings
  const bitrate = mapBitrate(options.bitrate ?? 64000)
  module._oc_encoder_ctl(encoderPtr, OPUS_SET_BITRATE_REQUEST, bitrate)

  if (options.complexity !== undefined) {
    module._oc_encoder_ctl(
      encoderPtr,
      OPUS_SET_COMPLEXITY_REQUEST,
      options.complexity
    )
  }

  if (options.vbr !== undefined) {
    module._oc_encoder_ctl(
      encoderPtr,
      OPUS_SET_VBR_REQUEST,
      options.vbr ? 1 : 0
    )
  }

  if (options.fec !== undefined) {
    module._oc_encoder_ctl(
      encoderPtr,
      OPUS_SET_INBAND_FEC_REQUEST,
      options.fec ? 1 : 0
    )
  }

  if (options.dtx !== undefined) {
    module._oc_encoder_ctl(
      encoderPtr,
      OPUS_SET_DTX_REQUEST,
      options.dtx ? 1 : 0
    )
  }

  if (options.packetLossPercent !== undefined) {
    module._oc_encoder_ctl(
      encoderPtr,
      OPUS_SET_PACKET_LOSS_PERC_REQUEST,
      options.packetLossPercent
    )
  }

  // Scratch buffers (grow-only to avoid repeated malloc/free)
  let pcmPtr = 0
  let pcmBytes = 0
  let packetPtr = 0
  let packetBytes = 0
  let freed = false

  const ensurePcmBuffer = (requiredBytes: number): number => {
    if (requiredBytes > pcmBytes) {
      if (pcmPtr) module._free(pcmPtr)
      pcmPtr = module._malloc(requiredBytes)
      pcmBytes = requiredBytes
    }
    return pcmPtr
  }

  const ensurePacketBuffer = (requiredBytes: number): number => {
    if (requiredBytes > packetBytes) {
      if (packetPtr) module._free(packetPtr)
      packetPtr = module._malloc(requiredBytes)
      packetBytes = requiredBytes
    }
    return packetPtr
  }

  const assertLive = () => {
    if (freed) {
      throw new Error("Opus encoder has been freed")
    }
  }

  return {
    sampleRate,
    channels,
    frameSize,

    getLookahead(): number {
      assertLive()
      return module._oc_encoder_ctl_get_lookahead(encoderPtr)
    },

    encode(pcm: Int16Array, opts?: { frameSize?: number }): Uint8Array {
      assertLive()
      const actualFrameSize = opts?.frameSize ?? frameSize
      const expectedSamples = actualFrameSize * channels

      if (pcm.length !== expectedSamples) {
        throw new RangeError(
          `Expected ${expectedSamples} samples (${actualFrameSize} * ${channels}), got ${pcm.length}`
        )
      }

      const pcmBytesNeeded = pcm.byteLength
      const maxPacketBytes = 4000

      const pcmBuf = ensurePcmBuffer(pcmBytesNeeded)
      const packetBuf = ensurePacketBuffer(maxPacketBytes)

      module.HEAP16.set(pcm, pcmBuf >> 1)

      const encodedBytes = module._oc_encode(
        encoderPtr,
        pcmBuf,
        actualFrameSize,
        packetBuf,
        maxPacketBytes
      )

      if (encodedBytes < 0) {
        throw createOpusError(module, encodedBytes, "encode")
      }

      return module.HEAPU8.slice(packetBuf, packetBuf + encodedBytes)
    },

    encodeFloat(pcm: Float32Array, opts?: { frameSize?: number }): Uint8Array {
      assertLive()
      const actualFrameSize = opts?.frameSize ?? frameSize
      const expectedSamples = actualFrameSize * channels

      if (pcm.length !== expectedSamples) {
        throw new RangeError(
          `Expected ${expectedSamples} samples (${actualFrameSize} * ${channels}), got ${pcm.length}`
        )
      }

      const pcmBytesNeeded = pcm.byteLength
      const maxPacketBytes = 4000

      const pcmBuf = ensurePcmBuffer(pcmBytesNeeded)
      const packetBuf = ensurePacketBuffer(maxPacketBytes)

      module.HEAPF32.set(pcm, pcmBuf >> 2)

      const encodedBytes = module._oc_encode_float(
        encoderPtr,
        pcmBuf,
        actualFrameSize,
        packetBuf,
        maxPacketBytes
      )

      if (encodedBytes < 0) {
        throw createOpusError(module, encodedBytes, "encodeFloat")
      }

      return module.HEAPU8.slice(packetBuf, packetBuf + encodedBytes)
    },

    free() {
      if (freed) return

      if (pcmPtr) module._free(pcmPtr)
      if (packetPtr) module._free(packetPtr)
      module._oc_destroy_encoder(encoderPtr)

      freed = true
    },
  }
}

export async function createOpusDecoder(
  options: OpusDecoderOptions
): Promise<OpusDecoderHandle> {
  const module = await getModule()

  const sampleRate = options.sampleRate
  const channels = options.channels

  // Create decoder
  const errorPtr = module._malloc(4)
  let decoderPtr: number

  try {
    decoderPtr = module._oc_create_decoder(sampleRate, channels, errorPtr)
    const error = module.HEAP32[errorPtr >> 2]!

    if (!decoderPtr || error !== 0) {
      throw createOpusError(module, error, "createDecoder")
    }
  } finally {
    module._free(errorPtr)
  }

  // Scratch buffers
  let pcmPtr = 0
  let pcmBytes = 0
  let packetPtr = 0
  let packetBytes = 0
  let freed = false

  const ensurePcmBuffer = (requiredBytes: number): number => {
    if (requiredBytes > pcmBytes) {
      if (pcmPtr) module._free(pcmPtr)
      pcmPtr = module._malloc(requiredBytes)
      pcmBytes = requiredBytes
    }
    return pcmPtr
  }

  const ensurePacketBuffer = (requiredBytes: number): number => {
    if (requiredBytes > packetBytes) {
      if (packetPtr) module._free(packetPtr)
      packetPtr = module._malloc(requiredBytes)
      packetBytes = requiredBytes
    }
    return packetPtr
  }

  const assertLive = () => {
    if (freed) {
      throw new Error("Opus decoder has been freed")
    }
  }

  return {
    decode(packet: Uint8Array, frameSize: number): Int16Array {
      assertLive()
      const outputSamples = frameSize * channels
      const pcmBytesNeeded = outputSamples * 2 // Int16 = 2 bytes per sample

      const packetBuf = ensurePacketBuffer(packet.byteLength)
      const pcmBuf = ensurePcmBuffer(pcmBytesNeeded)

      module.HEAPU8.set(packet, packetBuf)

      const decodedSamples = module._oc_decode(
        decoderPtr,
        packetBuf,
        packet.byteLength,
        pcmBuf,
        frameSize,
        0 // decode_fec
      )

      if (decodedSamples < 0) {
        throw createOpusError(module, decodedSamples, "decode")
      }

      return module.HEAP16.slice(pcmBuf >> 1, (pcmBuf >> 1) + outputSamples)
    },

    decodeFloat(packet: Uint8Array, frameSize: number): Float32Array {
      assertLive()
      const outputSamples = frameSize * channels
      const pcmBytesNeeded = outputSamples * 4 // Float32 = 4 bytes per sample

      const packetBuf = ensurePacketBuffer(packet.byteLength)
      const pcmBuf = ensurePcmBuffer(pcmBytesNeeded)

      module.HEAPU8.set(packet, packetBuf)

      const decodedSamples = module._oc_decode_float(
        decoderPtr,
        packetBuf,
        packet.byteLength,
        pcmBuf,
        frameSize,
        0 // decode_fec
      )

      if (decodedSamples < 0) {
        throw createOpusError(module, decodedSamples, "decodeFloat")
      }

      return module.HEAPF32.slice(pcmBuf >> 2, (pcmBuf >> 2) + outputSamples)
    },

    decodePacketLoss(frameSize: number): Int16Array {
      assertLive()
      const outputSamples = frameSize * channels
      const pcmBytesNeeded = outputSamples * 2

      const pcmBuf = ensurePcmBuffer(pcmBytesNeeded)

      // Pass null packet for PLC
      const decodedSamples = module._oc_decode(
        decoderPtr,
        0, // null pointer
        0, // length 0
        pcmBuf,
        frameSize,
        0
      )

      if (decodedSamples < 0) {
        throw createOpusError(module, decodedSamples, "decodePacketLoss")
      }

      return module.HEAP16.slice(pcmBuf >> 1, (pcmBuf >> 1) + outputSamples)
    },

    free() {
      if (freed) return

      if (pcmPtr) module._free(pcmPtr)
      if (packetPtr) module._free(packetPtr)
      module._oc_destroy_decoder(decoderPtr)

      freed = true
    },
  }
}
