/**
 * Type declarations for libopus WASM module
 * Generated by Emscripten
 */

export interface LibopusModule {
  // Memory heaps
  HEAP16: Int16Array
  HEAP32: Int32Array
  HEAPF32: Float32Array
  HEAPU8: Uint8Array

  // Memory management
  _malloc(size: number): number
  _free(ptr: number): void

  // String utilities
  UTF8ToString(ptr: number): string

  // Encoder functions
  _oc_create_encoder(
    sampleRate: number,
    channels: number,
    application: number,
    errorPtr: number
  ): number
  _oc_destroy_encoder(encoder: number): void
  _oc_encode(
    encoder: number,
    pcm: number,
    frameSize: number,
    data: number,
    maxDataBytes: number
  ): number
  _oc_encode_float(
    encoder: number,
    pcm: number,
    frameSize: number,
    data: number,
    maxDataBytes: number
  ): number
  _oc_encoder_ctl(encoder: number, request: number, value: number): number
  _oc_encoder_ctl_get_bitrate(encoder: number): number
  _oc_encoder_ctl_get_lookahead(encoder: number): number
  _oc_encoder_ctl_get_in_dtx(encoder: number): number

  // Decoder functions
  _oc_create_decoder(
    sampleRate: number,
    channels: number,
    errorPtr: number
  ): number
  _oc_destroy_decoder(decoder: number): void
  _oc_decode(
    decoder: number,
    data: number,
    len: number,
    pcm: number,
    frameSize: number,
    decodeFec: number
  ): number
  _oc_decode_float(
    decoder: number,
    data: number,
    len: number,
    pcm: number,
    frameSize: number,
    decodeFec: number
  ): number
  _oc_decoder_ctl(decoder: number, request: number, value: number): number

  // Packet utilities
  _oc_packet_get_bandwidth(data: number): number
  _oc_packet_get_nb_channels(data: number): number
  _oc_packet_get_nb_frames(data: number, len: number): number
  _oc_packet_get_nb_samples(
    data: number,
    len: number,
    sampleRate: number
  ): number
  _oc_packet_get_samples_per_frame(data: number, sampleRate: number): number
  _oc_packet_parse(data: number, len: number): number
  _oc_packet_validate_decode(
    data: number,
    len: number,
    sampleRate: number
  ): number

  // Error handling
  _oc_strerror(code: number): number

  // Version info
  _oc_get_version_string(): number
}

declare function createLibopusModule(): Promise<LibopusModule>
export default createLibopusModule
