/**
 * Type declarations for libflac WASM module
 * Generated by Emscripten
 */

export interface LibFlacModule {
  // Memory heaps
  HEAP16: Int16Array
  HEAP32: Int32Array
  HEAPU8: Uint8Array

  // Memory management
  _malloc(size: number): number
  _free(ptr: number): void

  // String utilities
  UTF8ToString(ptr: number): string

  // FLAC stream encoder functions
  _FLAC__stream_encoder_new(): number
  _FLAC__stream_encoder_delete(encoder: number): void
  _FLAC__stream_encoder_set_channels(encoder: number, channels: number): number
  _FLAC__stream_encoder_set_bits_per_sample(
    encoder: number,
    bitsPerSample: number
  ): number
  _FLAC__stream_encoder_set_sample_rate(
    encoder: number,
    sampleRate: number
  ): number
  _FLAC__stream_encoder_set_compression_level(
    encoder: number,
    level: number
  ): number
  _FLAC__stream_encoder_set_total_samples_estimate(
    encoder: number,
    totalSamples: bigint
  ): number
  _FLAC__stream_encoder_set_streamable_subset(
    encoder: number,
    value: number
  ): number
  _FLAC__stream_encoder_process_interleaved(
    encoder: number,
    buffer: number,
    samples: number
  ): number
  _FLAC__stream_encoder_finish(encoder: number): number
  _FLAC__stream_encoder_get_state(encoder: number): number

  // Custom wrapper functions (from flac_wasm_wrapper.c)
  _fc_init_encoder(encoder: number): number
  _fc_get_output_ptr(): number
  _fc_get_output_size(): number
  _fc_reset_output(): void
}

declare function createLibFlacModule(): Promise<LibFlacModule>
export default createLibFlacModule
